name: flutter_capstone_6
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.21.0-nullsafety.1
  google_fonts: ^3.0.1
  dio: ^4.0.6
  provider: ^6.0.4
  json_annotation: ^4.0.1
  pin_code_fields: ^7.4.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^4.1.3
  build_runner: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/splash/
    - assets/login/
    - assets/icons/
    - assets/register/
    - assets/register_verification/
    - assets/forgot_password/
    - assets/onboarding/
    - assets/home/
    - assets/explore/
    - assets/booking_class/